### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by T9Air** [T9Air/MarkEd#1]
The UI is currently very basic and needs to be greatly improved. The color theme should be similar to vscode. The main window should be black, and the textboxes should be a slightly lighter black/dark gray.

**Comment by Proffesor-Howard-J-Yont** [comment]
hi

**Comment by Proffesor-Howard-J-Yont** [comment]
How do i view the program?

**Comment by T9Air** [comment]
@Proffesor-Howard-J-Yont The line numbers are not so responsive, and the numbers should fill up the whole textbox even before you type on that line
